
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - pip
  - samtools=1.12 
  - bwa=0.7.17 
  - fastqc=0.11.8 
  - sra-tools=2.11.0 
  - cutadapt=3.4 
  - bowtie2=2.4.2 
  - hisat2=2.2.1 
  - subread=2.0.1
  - entrez-direct=13.9
  - minimap2=2.18
  - pip:
    - NanoPlot

